name: simpe_state_management
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  hooks_riverpod: 2.3.8

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
